// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hQjyVH-ilOLPcRqse5PIhYEajkSB5yU',
    appId: '1:1092437271093:web:79a1f14eff90cf294ec77c',
    messagingSenderId: '1092437271093',
    projectId: 'chat-app-b4a29',
    authDomain: 'chat-app-b4a29.firebaseapp.com',
    storageBucket: 'chat-app-b4a29.appspot.com',
    measurementId: 'G-BFYB5XNS6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDoNuT2wtTfG2TDLHIBXH4M9R0xOnuDXs',
    appId: '1:1092437271093:android:af1839064edef5ad4ec77c',
    messagingSenderId: '1092437271093',
    projectId: 'chat-app-b4a29',
    storageBucket: 'chat-app-b4a29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXoqoI4wXYUTdS0Xjq4kSje6lyh4iDsM',
    appId: '1:1092437271093:ios:0bf02cd71186f7a94ec77c',
    messagingSenderId: '1092437271093',
    projectId: 'chat-app-b4a29',
    storageBucket: 'chat-app-b4a29.appspot.com',
    iosClientId: '1092437271093-c01g3ml4tu7k1338sqpsb42m0liabrti.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeXoqoI4wXYUTdS0Xjq4kSje6lyh4iDsM',
    appId: '1:1092437271093:ios:0bf02cd71186f7a94ec77c',
    messagingSenderId: '1092437271093',
    projectId: 'chat-app-b4a29',
    storageBucket: 'chat-app-b4a29.appspot.com',
    iosClientId: '1092437271093-c01g3ml4tu7k1338sqpsb42m0liabrti.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
